stages:
  - make_assets
  - embed_reveal
  - docusaurus

build_dir: /build
output_type: last
output_dir: /output

make_assets:
  plugin: command
  options:
    command: make
    locations:
      - chapters/software-stack
      - content/chapters/data/lecture
      - chapters/compute
      - content/chapters/io/lecture
      - content/chapters/app-interact/lecture
    args:
      - all

embed_reveal:
  plugin: reveal_embed
  options:
    target: docusaurus
    extension: mdx
    build:
      Software-Stack: slides/Software-Stack
      Data: slides/Data
      Compute: slides/Compute
      IO: slides/IO
      Application-Interaction: slides/Application-Interaction

docusaurus:
  plugin: docusaurus
  options:
    course_name: SO
    sidebar: js
    structure:
      - Introduction: content/landing-page/README.md
      - Software Stack:
        - Slides: /build/embed_reveal/Software-Stack/Software-Stack.mdx
        - Lab 1 - Operating System Perspective:
            subsections:
              - Overview:
                  path: chapters/software-stack/overview/
                  extra:
                    - media/
                    - drills/questions/
                  subsections:
                    - Reading: reading/overview.md
                    - Drills:
                        path: drills/
                        subsections:
                          - Questions:
                              path: questions/
                              subsections:
                                - Software: software.md
              - Modern Software Stacks:
                  path: chapters/software-stack/modern-software-stacks
                  extra:
                    - media/
                  subsections:
                    - Reading: reading/modern-sw-stack.md
              - System Calls:
                  path: chapters/software-stack/system-calls
                  extra:
                    - media/
                    - drills/questions/
                    - drills/tasks/
                  subsections:
                    - Reading:
                        path: reading/
                        subsections:
                          - Basic System Calls: basic-syscall.md
                          - System Call Wrapper: syscall-wrapper.md
                          - Libcall-Syscall: libcall-syscall.md
                    - Drills:
                        path: drills/
                        subsections:
                          - Tasks:
                              path: tasks/
                              subsections:
                                - Basic Syscall/: basic-syscall/
                                - System Call Wrapper/: syscall-wrapper/
                          - Questions:
                              path: questions/
                              subsections:
                                - Libcall with Syscall: libcall-syscall.md
                                - Syscall Wrappers: syscall-wrapper.md
                                - Syscall ID: syscall-id.md
                                - Syscall Tool: syscall-tool.md
                                - Syscall Numbers: syscall-numbers.md
        - Lab 2 - Library Perspective:
            subsections:
              - Libraries:
                  path: chapters/software-stack/libraries
                  extra:
                    - media/
                    - drills/questions/
                  subsections:
                    - Guides:
                        path: guides/
                        subsections:
                          - Static-Dynamic/: static-dynamic/
                    - Drills:
                        path: drills/
                        subsections:
                          - Questions:
                              path: questions/
                              subsections:
                                - Dynamic Libraries: dynamic-libraries.md
                                - Static Executables: static-executables.md
              - Libc:
                  path: chapters/software-stack/libc
                  extra:
                    - media/
                    - drills/questions/
                    - drills/tasks/
                  subsections:
                    - Reading:
                        path: reading/
                        subsections:
                          - Common Functions: common-functions.md
                          - Libc: libc.md
                    - Drills:
                        path: drills/
                        subsections:
                          - Tasks:
                              path: tasks/
                              subsections:
                                - Common Functions/: common-functions/
                                - Libc/: libc/
                          - Questions:
                              path: questions/
                              subsections:
                                - printf System Call: printf-syscall.md
                                - strcpy System Call: strcpy-syscall.md
                                - printf vs write: printf-vs-write.md
                                - malloc: malloc.md
                                - Syscall Tool: syscall-tool.md
              - High-Level Languages:
                  path: chapters/software-stack/high-level-languages
                  extra:
                    - drills/questions/
                  subsections:
                    - Reading:
                        path: reading/
                        subsections:
                          - High-Level Languages: high-level-lang.md
                    - Drills:
                        path: drills/
                        subsections:
                          - Tasks:
                              path: tasks/
                              subsections:
                                - High-Level Languages/: high-level-lang/
                          - Questions:
                              path: questions/
                              subsections:
                                - Python Tools: python-tools.md
              - Applications:
                  path: chapters/software-stack/applications
                  extra:
                    - media/
                  subsections:
                    - Reading:
                        path: reading/
                        subsections:
                          - Applications: app-investigate.md
                    - Drills:
                        path: drills/
                        subsections:
                          - Tasks:
                              path: tasks/
                              subsections:
                                - Applications/: app-investigation/
      - Compute:
        - Slides: /build/embed_reveal/Compute/Compute.mdx
        - Overview:
            path: chapters/compute/overview/
            extra:
              - media/
            subsections:
              - Reading: reading/overview.md
        - Hardware Perspective:
            path: chapters/compute/hardware-perspective/
            extra:
              - media/
            subsections:
              - Reading: reading/hardware-perspective.md
         - Processes:
            path: chapters/compute/processes/
            extra:
            - media/
            - drills/
            subsections:
            - Reading: reading/processes.md
            - Drills:
                path: drills/
                subsections:
                    - Tasks:
                        path: tasks/
                    - Questions:
                        path: questions/
                        subsections:
                            - Cause of FileNotFoundError: cause-of-file-not-found-error.md
                            - create_sleepy Process Ending: create-sleepy-process-ending.md
                            - Parent of sleep Processes: parent-of-sleep-processes.md
                            - Process Creation: process-creation.md
                            - Processes Speedup: process-speedup.md
         - Threads:
            path: chapters/compute/threads
            extra:
                - drills/
                - guides/
                - media/
            subsections:
                - Tasks:
                    path: tasks/
                - Questions:
                    path: questions/
                    subsections:
                        - Seg Fault Exit Code: seg-fault-exit-code.md
                        - Thread Memory: thread-memory.md
                        - Threads Shared Data: threads-shared-data.md
                - Guides:
                    path: guides/
         - Usage of Processes and Threads in apache2:
            path: chapters/compute/processes-threads-apache2
            extra:
                - drills/
                - guides/
            subsections:
                - Reading: reading/processes-threads-apache2.md
                - Drills:
                    path: drills/
                    subsections:
                        - Tasks:
                            path: tasks/
                            subsections:
                                - Investigate apache2 Using strace/: apache2/
                        - Questions:
                            path: questions/
                            subsections:
                                - apache2 Document Root: apache2-strace.md
                - Guides:
                    path: guides/
                    subsections:
                        - apache2 Live Action: apache2/
         - Copy-on-Write:
            path: chapters/compute/copy-on-write
            extra:
                - drills/
                - guides/
                - media/
            subsections:
                - Reading: reading/copy-on-write.md
                - Drills:
                    path: drills/
                    subsections:
                        - Questions:
                            path: questions/
                            subsections:
                                - Child Faults After Write: child-faults-after-write.md
                                - Parent Faults before fork(): parent-faults-before-fork.md
                                - Always Shared Sections: sections-always-shared.md
                - Guides:
                    path: guides/
                    subsections:
                        - Fork faults/: fork-faults/
         - Synchronization:
            path: chapters/compute/synchronization
            extra:
                - drills/
                - guides/
                - media/
            subsections:
                - Reading: reading/synchronization.md
                - Drills:
                    path: drills/
                    subsections:
                        - Tasks:
                            path: tasks/
                            subsections:
                                - C - TLS on Demand/: race-condition/
                        - Questions:
                            path: questions/
                            subsections:
                                - Coarse vs Granular Critical Section: coarse-vs-granular-critical-section.md
                                - Both Condition and Mutex: notify-only-with-mutex.md
                                - Not Race Condition: not-race-condition.md
                                - Semaphore Equivalent: semaphore-equivalent.md
                                - TLS Synchronization: tls-synchronization.md
                                - TLS var Copies: tls-var-copies.md
                - Guides:
                    path: guides/
                    subsections:
                        - apache2 Simulator/: apache2-simulator/
        - User-Level Threads:
            path: chapters/compute/user-level-threads
            extra:
                - drills/
                - guides/
            subsections:
                - Reading: reading/user-level-threads.md
                - Drills:
                    path: drills/
                    subsections:
                        - Questions:
                            path: questions/
                            subsections:
                                - Fiber Strace: fiber-strace.md
                                - Sleeping on a Fiber: sleeping-on-a-fiber.md
                - Guides:
                    path: guides/
                    subsections:
                        - Interaction Between Threads and Fibers/: user-level-threads/
        - Arena:
            path: chapters/compute/arena
            extra:
                - drills/
                - media/
            subsections:
                - Reading: reading/arena.md
                - Drills:
                    path: drills/
                    subsections:
                        - Tasks:
                            path: tasks/
                        - Questions:
                            path: questions/
                            subsections:
                                - exec() Without fork(): exec-without-fork.md
                                - Mini-shell Stops After Command: mini-shell-stops-after-command.md
                                - Copy-on-write Flag for mmap(): mmap-cow-flag.md
                                - Who Calls execve in the Log of the Parent Process?: who-calls-execve-parent.md

      - Lecture:
          path: /build/embed_reveal
          subsections:
            - Data: Data/Data.mdx
            - IO: IO/IO.mdx
            - Application Interaction: Application-Interaction/Application-Interaction.mdx
      - Lab:
        - Setting up the Lab Environment: content/misc/lab-setup.md
        - Data:
            path: content/chapters/data/lab/content
            extra:
              - ../quiz
            subsections:
              - Overview: overview.md
              - Working with Memory: working-memory.md
              - Process Memory: process-memory.md
              - Investigate Memory: investigate-memory.md
              - Memory Security: memory-security.md
              - Arena: arena.md
        - IO:
            path: content/chapters/io/lab/content
            extra:
              - ../media
              - ../quiz
            subsections:
              - Overview: overview.md
              - File Handlers: file-handlers.md
              - File Descriptors: file-descriptors.md
              - Redirections: redirections.md
              - Pipes: pipes.md
              - Local IO in Action: local-io-in-action.md
              - Remote IO: remote-io.md
              - Networking 101: networking-101.md
              - Client-Server Model: client-server-model.md
              - Beyond Network Sockets: beyond-network-sockets.md
              - File Mappings: file-mappings.md
              - IO Internals: io-internals.md
              - Zero-Copy: zero-copy.md
              - Asynchronous IO: async-io.md
              - IO Multiplexing: io-multiplexing.md
              - Arena: arena.md
        - Application Interaction:
            path: content/chapters/app-interact/lab/content
            extra:
              - ../media
              - ../quiz
            subsections:
              - Overview: overview.md
              - Time Server: time-server.md
              - Password Cracker: password-cracker.md
              - The X Window System: x-window-system.md
              - D-Bus: dbus.md
              - OS Cloud: os-cloud.md
              - Arena: arena.md
      - Assignments:
          # These all have the same filename so we need to create separate
          # subdirectories for them, otherwise they will overwrite each other.
          # (See the trailing slash in the path.)
          subsections:
            - Mini Libc/: chapters/software-stack/libc/projects/mini-libc/
            - Memory Allocator/: content/assignments/memory-allocator/
            - Parallel Graph/: content/assignments/parallel-graph/
            - Mini Shell/: content/assignments/minishell/
            - Asynchronous Web Server/: content/assignments/async-web-server/
      - Exams:
          path: chapters/general/drills/tasks
          subsections:
            - Digital Forensics/: digital-forensics.md
            - Distributed System/: distributed-system.md
            - Aggregator Application/: aggregator-application.md
            - Benchmarking Application/: benchmarking-application.md
            - Database Application/: database-application.md
            - Application Investigator/: application-investigator.md
            - Network Performance Utility/: network-performance-utility.md
            - Nightly Builds System/: nightly-builds-system.md
            - User-level Threading Library/: user-level-threading-library.md
            - System Process Monitoring Tool/: system-process-monitoring-tool.md
            - Network Configurations Manager/: network-configurations-manager.md
            - FaaS Application/: faas-application.md
            - Industrial System/: industrial-system.md
            - Blockchain System/: blockchain-system.md
            - Supervisor-type Service/: supervisor-type-service.md
            - Header Analysis Application/: header-analysis-application.md
            - Extending an App Manager/: extending-an-app-manager.md
            - Backup System/: backup-system.md
            - File Changes Notifier/: file-changes-notifier.md
            - Intrusion Detection System/: intrusion-detection-system.md
            - Resource Monitor/: resource-monitor.md
            - Library Warmer/: library-warmer.md
            - Web GUI 1/: web-gui-1.md
            - Web GUI 2/: web-gui-2.md
            - Memory Deduplication/: memory-deduplication.md
            - Cloud System/: cloud-system.md
      - Hackathons:
          path: content/assignments
          subsections:
            - Lambda Function Loader/: lambda-function-loader/
      - Rules and Grading: content/misc/rules-and-grading.md
      - Resources: content/misc/resources.md
    static_assets:
      - slides/Compute: /build/make_assets/chapters/compute/_site
      - slides/Software-Stack: /build/make_assets/chapters/software-stack/_site
      - slides/Data: /build/make_assets/content/chapters/data/lecture/_site
      - slides/IO: /build/make_assets/content/chapters/io/lecture/_site
      - slides/Application-Interaction: /build/make_assets/content/chapters/app-interact/lecture/_site
    config_meta:
      title: Operating Systems
      url: http://localhost/
      baseUrl: /operating-systems/
      onBrokenLinks: warn
      onBrokenMarkdownLinks: warn
    config_socials:
      Main site: https://curs.upb.ro
      OCW: https://ocw.cs.pub.ro/courses/so
      Facebook: https://www.facebook.com/sisteme.de.operare/
    copyright_string: SO Team
